baseURL = 'https://astridsiegfreidhwh.github.io/'
languageCode = 'en-us'
title = 'astridsiegfreidhwh'
theme = "paper"
paginate = 5
DefaultContentLanguage = "en"
enableInlineShortcodes = true

[menu]
  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog/"
    weight = 10
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10
#  [[menu.main]]
#    identifier = "contact"
#    name = "Contact"
#    url = "/contact/"
#    weight = 10

[taxonomies]
  tag = "tags"
  series = "series"
  category = "categories"

[params]
  # color style
  color = 'white'                           # linen, wheat, gray, light

  # header social icons
  # twitter = 'YOUR_TWITTER_ID'               # twitter.com/YOUR_TWITTER_ID
  github = 'angellissa'                 # github.com/YOUR_GITHUB_ID
  # instagram = 'YOUR_INSTAGRAM_ID'           # instagram.com/YOUR_INSTAGRAM_ID
  # linkedin = 'YOUR_LINKEDIN_ID'             # linkedin.com/in/YOUR_LINKEDIN_ID
  # mastodon = 'YOUR_MASTODON_LINK'           # e.g. 'https://mastodon.instance/@xxx'
  rss = true                                # show rss icon

  # home page profile
  avatar = 'https://avatars.githubusercontent.com/u/132993530'                 # gravatar email or image url
  name = 'astridsiegfreidhwh'
  bio = ''

  # misc
  disableHLJS = true                        # disable highlight.js
  disablePostNavigation = true              # disable post navigation
  monoDarkIcon = true                       # show monochrome dark mode icon
  # gravatarCdn = 'https://avatars.githubusercontent.com/u/132981725'         # e.g. 'https://cdn.v2ex.com/gravatar/'
  # graphCommentId = ""  # use graph comment (disqus alternative)
  math = true                               # enable KaTeX math typesetting globally


[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true
    disableInlineCSS = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true